version: '3'

services:

  eventbus:
    image: rabbitmq:latest

  influx:
    image: hypriot/rpi-influxdb:latest

  history:
    image: brewblox/brewblox-history:rpi-latest
    depends_on:
      - influx
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  spark:
    image: brewblox/brewblox-devcon-spark:rpi-latest
    privileged: true
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spark"
    command:
      - "--simulation"
      - "--unit-system-file=config/celsius_system.txt"

  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=docker.localhost
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
