version: '3'

services:

  eventbus:
    image: rabbitmq

  influx:
    image: hypriot/rpi-influxdb
    # volumes:
    # - "./influxdb:/var/lib/influxdb"

  history:
    image: brewblox/brewblox-history:rpi-develop
    depends_on:
      - influx
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  game1:
    image: kargathia/game-controller:rpi-feature-controller
    privileged: true
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /game1"
    command:
      - "--name=game1"
      - "--controller-id=0"

  game2:
    image: kargathia/game-controller:rpi-feature-controller
    privileged: true
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /game2"
    command:
      - "--name=game2"
      - "--controller-id=1"

  lamp:
    image: kargathia/actuator-demo:rpi-feature-demo
    privileged: true
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /lamp"

  ui:
    image: brewblox/brewblox-ui:rpi-latest
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix: /"

  api:
    image: brewblox/brewblox-ui-api:rpi-latest
    labels:
      - "traefik.port=9090"
      - "traefik.frontend.rule=PathPrefix: /api"

  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
