version: '3'

services:
  influx:
    image: influxdb:alpine
    ports:
      - "8086:8086"
    volumes:
      - "./influxdb:/var/lib/influxdb"

  history:
    image: brewblox/brewblox-history:develop
    depends_on:
      - influx
    ports:
      - "80:5000"
