version: '3'

services:

  brewpi:
    image: brewpi/brewpi-ubuntu
    restart: always
    privileged: true
    volumes:
      - ~/brewpi-data:/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - "80:80"

  portainer:
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
