#!/bin/sh
set -e

command_exists() {
	command -v "$@" > /dev/null 2>&1
}

do_install() {
    echo "Executing BrewBlox install script..."

    if command_exists docker; then
        echo "Docker is already installed, skipping..."
    else
        curl -sSL https://get.docker.com | sh
    fi

    if id -nG "$USER" | grep -qw "docker"; then
        echo "$USER already belongs to the docker group, skipping..."
    else
        sudo usermod -aG docker $USER
    fi

    sudo apt install -y git python python-pip
    sudo pip install docker-compose

    git clone https://github.com/BrewBlox/brewblox-deployment.git
    cp -r brewblox-deployment/templates/* /home/$USER/
    rm -rf brewblox-deployment/

    cd /home/$USER/startup/
    /bin/bash ./configure_service.sh
    cd -

    echo
    echo "Installation finished."
    echo "Please restart your system before use."
    echo
}

do_install
