version: '3'

services:

  eventbus:
    image: rabbitmq:alpine
    restart: unless-stopped

  influx:
    image: influxdb
    restart: unless-stopped
    volumes:
    - ./influxdb:/var/lib/influxdb

  datastore:
    image: treehouses/couchdb
    restart: unless-stopped
    labels:
      - "traefik.port=5984"
      - "traefik.frontend.rule=PathPrefixStrip: /datastore"
    volumes:
      - ./couchdb:/opt/couchdb/data/

  spark:
    image: brewblox/brewblox-devcon-spark:rpi-feature-couchdb
    privileged: true
    depends_on:
      - eventbus
      - datastore
    restart: unless-stopped
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spark"
    command: >
      --device-host=192.168.0.66

  history:
    image: brewblox/brewblox-history:rpi-develop
    depends_on:
      - influx
      - eventbus
    restart: unless-stopped
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  ui:
    image: brewblox/brewblox-ui:rpi-feature-couchdb
    restart: unless-stopped
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix: /"

  traefik:
    image: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -c /dev/null --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
